version: "3.9"
services:
  my_service:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev_vscode
      args:
        USERNAME: ${USERNAME}
        UID: ${UID}
        GID: ${GID}
        MAIN_FOLDER_NAME: ${MAIN_FOLDER_NAME}
    container_name: "${DOCKER_COMPATIBLE_CONTAINER_NAME}_container"
    image: "${DOCKER_COMPATIBLE_CONTAINER_NAME}:v1.0"
    network_mode: "host"
    tty: true
    volumes:
     - "../src:/home/${USERNAME}/${MAIN_FOLDER_NAME}/src"
     - "../data:/home/${USERNAME}/${MAIN_FOLDER_NAME}/data"
     - "../logs:/home/${USERNAME}/${MAIN_FOLDER_NAME}/logs"
     - /tmp/.X11-unix:/tmp/.X11-unix:rw
     - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    working_dir: "/home/${USERNAME}/${MAIN_FOLDER_NAME}"
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
    runtime: nvidia
    command: /bin/bash